# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/mingj/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/183.4886.39/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/mingj/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/183.4886.39/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mingj/CLionProjects/ndnip_proxy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mingj/CLionProjects/ndnip_proxy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/mingj/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/183.4886.39/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/mingj/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/183.4886.39/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mingj/CLionProjects/ndnip_proxy/CMakeFiles /home/mingj/CLionProjects/ndnip_proxy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mingj/CLionProjects/ndnip_proxy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nip

# Build rule for target.
nip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nip
.PHONY : nip

# fast build rule for target.
nip/fast:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/build
.PHONY : nip/fast

#=============================================================================
# Target rules for targets named is

# Build rule for target.
is: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 is
.PHONY : is

# fast build rule for target.
is/fast:
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/build
.PHONY : is/fast

common/common.o: common/common.cpp.o

.PHONY : common/common.o

# target to build an object file
common/common.cpp.o:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/common/common.cpp.o
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/common/common.cpp.o
.PHONY : common/common.cpp.o

common/common.i: common/common.cpp.i

.PHONY : common/common.i

# target to preprocess a source file
common/common.cpp.i:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/common/common.cpp.i
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/common/common.cpp.i
.PHONY : common/common.cpp.i

common/common.s: common/common.cpp.s

.PHONY : common/common.s

# target to generate assembly for a file
common/common.cpp.s:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/common/common.cpp.s
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/common/common.cpp.s
.PHONY : common/common.cpp.s

ip_server/BoostTCPServerHelper.o: ip_server/BoostTCPServerHelper.cpp.o

.PHONY : ip_server/BoostTCPServerHelper.o

# target to build an object file
ip_server/BoostTCPServerHelper.cpp.o:
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/ip_server/BoostTCPServerHelper.cpp.o
.PHONY : ip_server/BoostTCPServerHelper.cpp.o

ip_server/BoostTCPServerHelper.i: ip_server/BoostTCPServerHelper.cpp.i

.PHONY : ip_server/BoostTCPServerHelper.i

# target to preprocess a source file
ip_server/BoostTCPServerHelper.cpp.i:
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/ip_server/BoostTCPServerHelper.cpp.i
.PHONY : ip_server/BoostTCPServerHelper.cpp.i

ip_server/BoostTCPServerHelper.s: ip_server/BoostTCPServerHelper.cpp.s

.PHONY : ip_server/BoostTCPServerHelper.s

# target to generate assembly for a file
ip_server/BoostTCPServerHelper.cpp.s:
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/ip_server/BoostTCPServerHelper.cpp.s
.PHONY : ip_server/BoostTCPServerHelper.cpp.s

ip_server/ip_server.o: ip_server/ip_server.cpp.o

.PHONY : ip_server/ip_server.o

# target to build an object file
ip_server/ip_server.cpp.o:
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/ip_server/ip_server.cpp.o
.PHONY : ip_server/ip_server.cpp.o

ip_server/ip_server.i: ip_server/ip_server.cpp.i

.PHONY : ip_server/ip_server.i

# target to preprocess a source file
ip_server/ip_server.cpp.i:
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/ip_server/ip_server.cpp.i
.PHONY : ip_server/ip_server.cpp.i

ip_server/ip_server.s: ip_server/ip_server.cpp.s

.PHONY : ip_server/ip_server.s

# target to generate assembly for a file
ip_server/ip_server.cpp.s:
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/ip_server/ip_server.cpp.s
.PHONY : ip_server/ip_server.cpp.s

ndn_ip_proxy/BoostTCPClientHelper.o: ndn_ip_proxy/BoostTCPClientHelper.cpp.o

.PHONY : ndn_ip_proxy/BoostTCPClientHelper.o

# target to build an object file
ndn_ip_proxy/BoostTCPClientHelper.cpp.o:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/ndn_ip_proxy/BoostTCPClientHelper.cpp.o
.PHONY : ndn_ip_proxy/BoostTCPClientHelper.cpp.o

ndn_ip_proxy/BoostTCPClientHelper.i: ndn_ip_proxy/BoostTCPClientHelper.cpp.i

.PHONY : ndn_ip_proxy/BoostTCPClientHelper.i

# target to preprocess a source file
ndn_ip_proxy/BoostTCPClientHelper.cpp.i:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/ndn_ip_proxy/BoostTCPClientHelper.cpp.i
.PHONY : ndn_ip_proxy/BoostTCPClientHelper.cpp.i

ndn_ip_proxy/BoostTCPClientHelper.s: ndn_ip_proxy/BoostTCPClientHelper.cpp.s

.PHONY : ndn_ip_proxy/BoostTCPClientHelper.s

# target to generate assembly for a file
ndn_ip_proxy/BoostTCPClientHelper.cpp.s:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/ndn_ip_proxy/BoostTCPClientHelper.cpp.s
.PHONY : ndn_ip_proxy/BoostTCPClientHelper.cpp.s

ndn_ip_proxy/ndn_ip_proxy.o: ndn_ip_proxy/ndn_ip_proxy.cpp.o

.PHONY : ndn_ip_proxy/ndn_ip_proxy.o

# target to build an object file
ndn_ip_proxy/ndn_ip_proxy.cpp.o:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/ndn_ip_proxy/ndn_ip_proxy.cpp.o
.PHONY : ndn_ip_proxy/ndn_ip_proxy.cpp.o

ndn_ip_proxy/ndn_ip_proxy.i: ndn_ip_proxy/ndn_ip_proxy.cpp.i

.PHONY : ndn_ip_proxy/ndn_ip_proxy.i

# target to preprocess a source file
ndn_ip_proxy/ndn_ip_proxy.cpp.i:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/ndn_ip_proxy/ndn_ip_proxy.cpp.i
.PHONY : ndn_ip_proxy/ndn_ip_proxy.cpp.i

ndn_ip_proxy/ndn_ip_proxy.s: ndn_ip_proxy/ndn_ip_proxy.cpp.s

.PHONY : ndn_ip_proxy/ndn_ip_proxy.s

# target to generate assembly for a file
ndn_ip_proxy/ndn_ip_proxy.cpp.s:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/ndn_ip_proxy/ndn_ip_proxy.cpp.s
.PHONY : ndn_ip_proxy/ndn_ip_proxy.cpp.s

protocol/BaseProtocolItem.o: protocol/BaseProtocolItem.cpp.o

.PHONY : protocol/BaseProtocolItem.o

# target to build an object file
protocol/BaseProtocolItem.cpp.o:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/protocol/BaseProtocolItem.cpp.o
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/protocol/BaseProtocolItem.cpp.o
.PHONY : protocol/BaseProtocolItem.cpp.o

protocol/BaseProtocolItem.i: protocol/BaseProtocolItem.cpp.i

.PHONY : protocol/BaseProtocolItem.i

# target to preprocess a source file
protocol/BaseProtocolItem.cpp.i:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/protocol/BaseProtocolItem.cpp.i
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/protocol/BaseProtocolItem.cpp.i
.PHONY : protocol/BaseProtocolItem.cpp.i

protocol/BaseProtocolItem.s: protocol/BaseProtocolItem.cpp.s

.PHONY : protocol/BaseProtocolItem.s

# target to generate assembly for a file
protocol/BaseProtocolItem.cpp.s:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/protocol/BaseProtocolItem.cpp.s
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/protocol/BaseProtocolItem.cpp.s
.PHONY : protocol/BaseProtocolItem.cpp.s

protocol/ProtocolHelper.o: protocol/ProtocolHelper.cpp.o

.PHONY : protocol/ProtocolHelper.o

# target to build an object file
protocol/ProtocolHelper.cpp.o:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/protocol/ProtocolHelper.cpp.o
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/protocol/ProtocolHelper.cpp.o
.PHONY : protocol/ProtocolHelper.cpp.o

protocol/ProtocolHelper.i: protocol/ProtocolHelper.cpp.i

.PHONY : protocol/ProtocolHelper.i

# target to preprocess a source file
protocol/ProtocolHelper.cpp.i:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/protocol/ProtocolHelper.cpp.i
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/protocol/ProtocolHelper.cpp.i
.PHONY : protocol/ProtocolHelper.cpp.i

protocol/ProtocolHelper.s: protocol/ProtocolHelper.cpp.s

.PHONY : protocol/ProtocolHelper.s

# target to generate assembly for a file
protocol/ProtocolHelper.cpp.s:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/protocol/ProtocolHelper.cpp.s
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/protocol/ProtocolHelper.cpp.s
.PHONY : protocol/ProtocolHelper.cpp.s

protocol/protocol.o: protocol/protocol.cpp.o

.PHONY : protocol/protocol.o

# target to build an object file
protocol/protocol.cpp.o:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/protocol/protocol.cpp.o
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/protocol/protocol.cpp.o
.PHONY : protocol/protocol.cpp.o

protocol/protocol.i: protocol/protocol.cpp.i

.PHONY : protocol/protocol.i

# target to preprocess a source file
protocol/protocol.cpp.i:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/protocol/protocol.cpp.i
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/protocol/protocol.cpp.i
.PHONY : protocol/protocol.cpp.i

protocol/protocol.s: protocol/protocol.cpp.s

.PHONY : protocol/protocol.s

# target to generate assembly for a file
protocol/protocol.cpp.s:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/protocol/protocol.cpp.s
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/protocol/protocol.cpp.s
.PHONY : protocol/protocol.cpp.s

utils/FileUtils.o: utils/FileUtils.cpp.o

.PHONY : utils/FileUtils.o

# target to build an object file
utils/FileUtils.cpp.o:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/utils/FileUtils.cpp.o
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/utils/FileUtils.cpp.o
.PHONY : utils/FileUtils.cpp.o

utils/FileUtils.i: utils/FileUtils.cpp.i

.PHONY : utils/FileUtils.i

# target to preprocess a source file
utils/FileUtils.cpp.i:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/utils/FileUtils.cpp.i
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/utils/FileUtils.cpp.i
.PHONY : utils/FileUtils.cpp.i

utils/FileUtils.s: utils/FileUtils.cpp.s

.PHONY : utils/FileUtils.s

# target to generate assembly for a file
utils/FileUtils.cpp.s:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/utils/FileUtils.cpp.s
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/utils/FileUtils.cpp.s
.PHONY : utils/FileUtils.cpp.s

utils/JSONCPPHelper.o: utils/JSONCPPHelper.cpp.o

.PHONY : utils/JSONCPPHelper.o

# target to build an object file
utils/JSONCPPHelper.cpp.o:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/utils/JSONCPPHelper.cpp.o
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/utils/JSONCPPHelper.cpp.o
.PHONY : utils/JSONCPPHelper.cpp.o

utils/JSONCPPHelper.i: utils/JSONCPPHelper.cpp.i

.PHONY : utils/JSONCPPHelper.i

# target to preprocess a source file
utils/JSONCPPHelper.cpp.i:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/utils/JSONCPPHelper.cpp.i
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/utils/JSONCPPHelper.cpp.i
.PHONY : utils/JSONCPPHelper.cpp.i

utils/JSONCPPHelper.s: utils/JSONCPPHelper.cpp.s

.PHONY : utils/JSONCPPHelper.s

# target to generate assembly for a file
utils/JSONCPPHelper.cpp.s:
	$(MAKE) -f CMakeFiles/nip.dir/build.make CMakeFiles/nip.dir/utils/JSONCPPHelper.cpp.s
	$(MAKE) -f CMakeFiles/is.dir/build.make CMakeFiles/is.dir/utils/JSONCPPHelper.cpp.s
.PHONY : utils/JSONCPPHelper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... nip"
	@echo "... is"
	@echo "... common/common.o"
	@echo "... common/common.i"
	@echo "... common/common.s"
	@echo "... ip_server/BoostTCPServerHelper.o"
	@echo "... ip_server/BoostTCPServerHelper.i"
	@echo "... ip_server/BoostTCPServerHelper.s"
	@echo "... ip_server/ip_server.o"
	@echo "... ip_server/ip_server.i"
	@echo "... ip_server/ip_server.s"
	@echo "... ndn_ip_proxy/BoostTCPClientHelper.o"
	@echo "... ndn_ip_proxy/BoostTCPClientHelper.i"
	@echo "... ndn_ip_proxy/BoostTCPClientHelper.s"
	@echo "... ndn_ip_proxy/ndn_ip_proxy.o"
	@echo "... ndn_ip_proxy/ndn_ip_proxy.i"
	@echo "... ndn_ip_proxy/ndn_ip_proxy.s"
	@echo "... protocol/BaseProtocolItem.o"
	@echo "... protocol/BaseProtocolItem.i"
	@echo "... protocol/BaseProtocolItem.s"
	@echo "... protocol/ProtocolHelper.o"
	@echo "... protocol/ProtocolHelper.i"
	@echo "... protocol/ProtocolHelper.s"
	@echo "... protocol/protocol.o"
	@echo "... protocol/protocol.i"
	@echo "... protocol/protocol.s"
	@echo "... utils/FileUtils.o"
	@echo "... utils/FileUtils.i"
	@echo "... utils/FileUtils.s"
	@echo "... utils/JSONCPPHelper.o"
	@echo "... utils/JSONCPPHelper.i"
	@echo "... utils/JSONCPPHelper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

